DROP TABLE IF EXISTS `blog_user`;
CREATE TABLE `blog_user` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_CODE` varchar(32) DEFAULT NULL,
  `USER_NAME` varchar(50) DEFAULT NULL,
  `USER_PWD` varchar(50) DEFAULT NULL,
  `MAIL` varchar(150) DEFAULT NULL,
  `ADDR` varchar(255) DEFAULT NULL,
  `BORN` varchar(60) DEFAULT NULL,
  `IN_DATE` datetime DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `USER_TYPE` int(11) DEFAULT NULL,
  `USER_STATUS` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;
